apiVersion: v1
data:
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::123456789012:role/tst-eks-node-group-2-euc1"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::123456789012:role/AWSReservedSSO_AdministratorAccess_45473fbe2cd57e20"
      "username": "okta-admin"
    - "groups": []
      "rolearn": "arn:aws:iam::123456789012:role/AWSReservedSSO_DevSecOps_1f20c82d245f99ba"
      "username": "okta-devops"
    - "groups": []
      "rolearn": "arn:aws:iam::123456789012:role/AWSReservedSSO_Developer_ec41ed98cd73b43c"
      "username": "okta-dev"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::123456789012:role/okta-admin"
      "username": "okta-admin"
      "rolearn": "arn:aws:iam::123456789012:role/okta-readonly"
      "username": "okta-readonly"
    - "groups": []
      "rolearn": "arn:aws:iam::123456789012:role/okta-dev"
      "username": "okta-dev"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::123456789012:user/terraform"
      "username": "terraform"
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  
